outcome = "sport_kat_c"
decimal_places = 2
single_label_scoring = "f1_weighted"
multi_label = True
ml_smote = False
verbose = 2
random_state = 93
nfolds = 3
categorical_features = ['edu', 'sex']
imputer_max_iter = 5
goal_vars = ['Zind_fitheal', 'Zind_figap', 'Zind_disstre', 'Zind_actenj', 'Zind_compperf', 'Zind_aes', 'Zind_con']